spring.application.name=BookingSystem
cloud-name: ddpckjxeg
api-key: 312136421383332
api-secret: D9Zq9PRN8z_blfiN45T_EtzMimM

#------------------------ Database --------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/BookingSystem
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
#-------------------------------------------------------

#-------------------- Console Setup --------------------
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=\
%clr(%d{HH:mm:ss}){faint} \
%clr(%5p){highlight} \
%clr([%15.15t]){faint} \
%clr(%-30logger{0}){cyan} \
%clr(:){faint} %m%n
#-------------------------------------------------------

#------------- Environment variables -------------------
BEARER_PREFIX=Bearer 
SECRET_KEY = "my-secret-key-my-secret-key-my-secret-key"
EXPIRATION_TOKEN_TIME = 10800000
#-------------------------------------------------------

#---------------- Admin Account ------------------------
SUPERADMIN_USERNAME=SuperAdmin
SUPERADMIN_EMAIL=admin@gmail.com
SUPERADMIN_PASSWORD=Ahmed@123
#-------------------------------------------------------

